In [1]:
import pandas as pd
import numpy as np

GroupBy in Pandas

In [3]:
data={
    "Name":["Aman","Bob","Charlie","David","Eve",None,"Sameer"],
    "Age":[25,30,None,40,45,24,28],
    "Marks":[85,90,78,None,92,88,80],
    "Subject":["Math","Science","History","Math",None,"Social Science","Science"]
}
df=pd.DataFrame(data)
df

      Name   Age  Marks         Subject
0     Aman  25.0   85.0            Math
1      Bob  30.0   90.0         Science
2  Charlie   NaN   78.0         History
3    David  40.0    NaN            Math
4      Eve  45.0   92.0             NaN
5      NaN  24.0   88.0  Social Science
6   Sameer  28.0   80.0         Science

In [4]:
#basic groupby
df.groupby("Subject")['Marks'].mean()

Subject
History           78.0
Math              85.0
Science           85.0
Social Science    88.0
Name: Marks, dtype: float64

In [5]:
df.groupby("Subject")["Marks"].count()

Subject
History           1
Math              1
Science           2
Social Science    1
Name: Marks, dtype: int64

In [6]:
#Multiple Aggregations
df.groupby("Subject")["Marks"].agg(["mean","max","min"])

                mean   max   min
Subject
History         78.0  78.0  78.0
Math            85.0  85.0  85.0
Science         85.0  90.0  80.0
Social Science  88.0  88.0  88.0

In [ ]:
#adding count here to see how many students are there in each subject along with mean, max and min marks
df.groupby('Subject')['Marks'].agg(['mean', 'max', 'min', 'count'])

                mean   max   min  count
Subject
History         78.0  78.0  78.0      1
Math            85.0  85.0  85.0      1
Science         85.0  90.0  80.0      2
Social Science  88.0  88.0  88.0      1

In [8]:
#Group by multiple columns
df.groupby(['Subject', 'Age'])['Marks'].mean()

Subject         Age
Math            25.0    85.0
                40.0     NaN
Science         28.0    80.0
                30.0    90.0
Social Science  24.0    88.0
Name: Marks, dtype: float64