In [1]:
import numpy as np
import pandas as pd

TechCorp HR Data

In [3]:
hr_data = {"Name":["John","Alice","Bob",None,"Eve","Charlie","David",None,"Aman","Anand"],
           "Department":["HR","Sales","IT","HR","Finance","Sales","Finance","HR","IT","Sales"],
           "Role":["Manager","Executive","Analyst","Executive","Developer","Manager","Analyst","Developer","Executive","Manager"],
           "Experience":[5,3,2,4,8,6,1,2,3,7],
           "Salary":[70000,50000,40000,60000,90000,80000,35000,45000,55000,75000],
           "Score":[85,90,None,88,92,None,75,82,89,91]
           }
df = pd.DataFrame(hr_data)
df

      Name Department       Role  Experience  Salary  Score
0     John         HR    Manager           5   70000   85.0
1    Alice      Sales  Executive           3   50000   90.0
2      Bob         IT    Analyst           2   40000    NaN
3      NaN         HR  Executive           4   60000   88.0
4      Eve    Finance  Developer           8   90000   92.0
5  Charlie      Sales    Manager           6   80000    NaN
6    David    Finance    Analyst           1   35000   75.0
7      NaN         HR  Developer           2   45000   82.0
8     Aman         IT  Executive           3   55000   89.0
9    Anand      Sales    Manager           7   75000   91.0

excersise ques part1

Basics Averages

In [4]:
df.groupby("Department")["Salary"].mean()

Department
Finance    62500.000000
HR         58333.333333
IT         47500.000000
Sales      68333.333333
Name: Salary, dtype: float64

In [5]:
df.groupby("Role")["Score"].mean()

Role
Analyst      75.0
Developer    87.0
Executive    89.0
Manager      88.0
Name: Score, dtype: float64

Counting and Sizing

In [7]:

df.groupby("Department")['Score'].count()

Department
Finance    2
HR         3
IT         1
Sales      2
Name: Score, dtype: int64

In [8]:
df.groupby("Department").size()

Department
Finance    2
HR         3
IT         2
Sales      3
dtype: int64

excercise ques part2

multiple aggregations

In [ ]:
df.groupby("Department")['Salary'].agg(['mean','max','min','count'])

                    mean    max    min  count
Department
Finance     62500.000000  90000  35000      2
HR          58333.333333  70000  45000      3
IT          47500.000000  55000  40000      2
Sales       68333.333333  80000  50000      3

In [13]:
df.groupby('Role')['Score'].agg(['mean','max','min','count'])

           mean   max   min  count
Role
Analyst    75.0  75.0  75.0      1
Developer  87.0  92.0  82.0      2
Executive  89.0  90.0  88.0      3
Manager    88.0  91.0  85.0      2

In [11]:
#average salary grouped by both department and role
df.groupby(['Department','Role'])['Salary'].mean()

Department  Role
Finance     Analyst      35000.0
            Developer    90000.0
HR          Developer    45000.0
            Executive    60000.0
            Manager      70000.0
IT          Analyst      40000.0
            Executive    55000.0
Sales       Executive    50000.0
            Manager      77500.0
Name: Salary, dtype: float64

In [12]:
#average performance score grouped by both department and experience level
df.groupby(['Department','Experience'])['Score'].mean()

Department  Experience
Finance     1             75.0
            8             92.0
HR          2             82.0
            4             88.0
            5             85.0
IT          2              NaN
            3             89.0
Sales       3             90.0
            6              NaN
            7             91.0
Name: Score, dtype: float64